"""Build the SPY drawdown-regime research notebook.

Run:
    python notebooks/_build_spy_drawdown_regime_book.py
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = PROJECT_ROOT / "notebooks" / "spy_drawdown_regime_book.ipynb"


def md(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source)


def code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source)


def build_notebook() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    cells: list[nbf.NotebookNode] = []

    cells.append(
        md(
            "# SPY Drawdown Regimes, VIX Pace, Credit Pace, and Sector Spillover\n\n"
            "**Goal.** Test three concrete ideas without forward-looking bias:\n"
            "1. Drawdowns that start from stronger markets should be shallower or recover faster than drawdowns that begin from weaker backdrops.\n"
            "2. Faster changes in VIX and credit conditions should help explain whether a drawdown becomes a quick shock or a deeper, slower unwind.\n"
            "3. Sector ETFs that are already stretched versus SPY should react differently during SPY drawdown windows, especially in ratio terms.\n\n"
            "This notebook is a Kaggle-style walkthrough of the research outputs generated by `spy_drawdown_regime_research.py`."
        )
    )

    cells.append(md("## 1. Load the research outputs"))
    cells.append(
        code(
            "import json\n"
            "from pathlib import Path\n"
            "\n"
            "import matplotlib.pyplot as plt\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import seaborn as sns\n"
            "from IPython.display import display\n"
            "\n"
            "plt.rcParams.update({\n"
            "    'figure.figsize': (12, 5),\n"
            "    'figure.dpi': 120,\n"
            "    'axes.grid': True,\n"
            "    'grid.alpha': 0.20,\n"
            "    'axes.spines.top': False,\n"
            "    'axes.spines.right': False,\n"
            "    'font.size': 10,\n"
            "})\n"
            "sns.set_theme(style='whitegrid', context='notebook')\n"
            "pd.options.display.float_format = '{:,.4f}'.format\n"
            "\n"
            "PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "RESEARCH_DIR = PROJECT_ROOT / 'outputs' / 'spy_drawdown_regime_research'\n"
            "print('research dir:', RESEARCH_DIR)"
        )
    )
    cells.append(
        code(
            "with open(RESEARCH_DIR / 'spy_drawdown_regime_summary.json', encoding='utf-8') as f:\n"
            "    summary = json.load(f)\n"
            "\n"
            "panel = pd.read_csv(RESEARCH_DIR / 'drawdown_daily_panel.csv', parse_dates=['signal_date', 'entry_date'])\n"
            "episodes = pd.read_csv(RESEARCH_DIR / 'spy_drawdown_episodes.csv', parse_dates=['peak_date', 'onset_date', 'trough_date', 'recovery_date'])\n"
            "strength_summary = pd.read_csv(RESEARCH_DIR / 'drawdown_strength_summary.csv')\n"
            "combined_summary = pd.read_csv(RESEARCH_DIR / 'drawdown_combined_regime_summary.csv')\n"
            "hypothesis_summary = pd.read_csv(RESEARCH_DIR / 'hypothesis_test_summary.csv')\n"
            "pace_summary = pd.read_csv(RESEARCH_DIR / 'pace_factor_summary.csv')\n"
            "sector_regime = pd.read_csv(RESEARCH_DIR / 'sector_regime_ratio_summary.csv')\n"
            "sector_stretch = pd.read_csv(RESEARCH_DIR / 'sector_stretch_summary.csv')\n"
            "sector_stretch_effect = pd.read_csv(RESEARCH_DIR / 'sector_stretch_effect_summary.csv')\n"
            "sector_episode = pd.read_csv(RESEARCH_DIR / 'sector_drawdown_episode_ratios.csv', parse_dates=['peak_date', 'onset_date', 'trough_date', 'recovery_date'])\n"
            "\n"
            "headline = pd.DataFrame({\n"
            "    'metric': ['panel rows', 'episodes', 'drawdown threshold', 'lookback window', 'sector observations'],\n"
            "    'value': [summary['rows'], summary['episode_count'], summary['drawdown_threshold'], summary['lookback_window'], len(sector_episode)],\n"
            "})\n"
            "display(headline)"
        )
    )

    cells.append(
        md(
            "## 2. Research guardrails\n\n"
            "The study is descriptive, but the state labels are still point-in-time.\n"
            "1. Market strength and fragility are measured using only trailing information available on the peak or onset date.\n"
            "2. Drawdown depth, speed, and recovery are evaluated after the episode ends, but no forward data leaks into the regime labels.\n"
            "3. Sector stretch is measured from the sector-to-SPY ratio at drawdown onset, not from future relative performance."
        )
    )

    cells.append(md("## 3. Does a stronger starting market change the drawdown profile?"))
    cells.append(
        code(
            "display(strength_summary.round(4))\n"
            "display(hypothesis_summary)\n"
            "\n"
            "fig, axes = plt.subplots(1, 3, figsize=(15.5, 4.8))\n"
            "sns.barplot(data=strength_summary, x='pre_drawdown_market_strength_regime', y='avg_max_drawdown', hue='pre_drawdown_market_strength_regime', dodge=False, legend=False, palette='crest', ax=axes[0])\n"
            "axes[0].set_title('Average drawdown depth by pre-drawdown regime')\n"
            "axes[0].set_xlabel('')\n"
            "axes[0].set_ylabel('average max drawdown')\n"
            "\n"
            "sns.barplot(data=strength_summary, x='pre_drawdown_market_strength_regime', y='avg_peak_to_trough_days', hue='pre_drawdown_market_strength_regime', dodge=False, legend=False, palette='mako', ax=axes[1])\n"
            "axes[1].set_title('Peak-to-trough duration')\n"
            "axes[1].set_xlabel('')\n"
            "axes[1].set_ylabel('days')\n"
            "\n"
            "sns.barplot(data=strength_summary, x='pre_drawdown_market_strength_regime', y='avg_drawdown_speed', hue='pre_drawdown_market_strength_regime', dodge=False, legend=False, palette='rocket', ax=axes[2])\n"
            "axes[2].set_title('Drawdown speed per day')\n"
            "axes[2].set_xlabel('')\n"
            "axes[2].set_ylabel('abs(drawdown) / day')\n"
            "plt.tight_layout()\n"
            "plt.show()"
        )
    )

    cells.append(
        md(
            "**Interpretation.**\n\n"
            "The output usually splits the question into two different mechanisms: depth versus speed. Weak-market drawdowns can be materially deeper and take longer to fully repair, while strong-market drawdowns can still happen fast because shock repricing is sharp when positioning is crowded."
        )
    )

    cells.append(md("## 4. Add the fragility tier: calm, fragile, or stress"))
    cells.append(
        code(
            "display(combined_summary.round(4))\n"
            "\n"
            "fig, axes = plt.subplots(1, 2, figsize=(14.5, 5.0))\n"
            "sns.barplot(data=combined_summary, y='pre_drawdown_combined_regime', x='avg_max_drawdown', hue='pre_drawdown_market_strength_regime', ax=axes[0])\n"
            "axes[0].set_title('Average max drawdown by strength + fragility regime')\n"
            "axes[0].set_xlabel('average max drawdown')\n"
            "axes[0].set_ylabel('')\n"
            "\n"
            "sns.barplot(data=combined_summary, y='pre_drawdown_combined_regime', x='recovered_within_60d_rate', hue='pre_drawdown_market_strength_regime', ax=axes[1])\n"
            "axes[1].set_title('Recovery within 60 trading days')\n"
            "axes[1].set_xlabel('recovery rate')\n"
            "axes[1].set_ylabel('')\n"
            "plt.tight_layout()\n"
            "plt.show()"
        )
    )

    cells.append(md("## 5. Does VIX pace or credit pace explain what comes next?"))
    cells.append(
        code(
            "display(pace_summary.round(4))\n"
            "\n"
            "heatmap = pace_summary.pivot(index='factor', columns='outcome', values='correlation')\n"
            "fig, ax = plt.subplots(figsize=(11.5, 4.5))\n"
            "sns.heatmap(heatmap, annot=True, fmt='.2f', cmap='RdYlBu_r', center=0.0, ax=ax)\n"
            "ax.set_title('Correlation of onset pace factors with drawdown outcomes')\n"
            "ax.set_xlabel('outcome')\n"
            "ax.set_ylabel('')\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "bucket_view = pace_summary.loc[pace_summary['outcome'].isin(['max_drawdown_abs', 'drawdown_speed_from_peak_per_day', 'recovered_within_60d'])].copy()\n"
            "display(bucket_view[['factor', 'outcome', 'high_bucket_mean', 'low_bucket_mean', 'high_minus_low']].round(4))"
        )
    )

    cells.append(
        md(
            "**Interpretation.**\n\n"
            "Higher VIX pace is usually the cleanest warning for a fast break. Credit pace often looks weaker for depth, but it can still matter for persistence and the character of the recovery. In other words, VIX pace tends to explain the *violence* of the move, while credit deterioration helps explain whether the backdrop is structurally sick."
        )
    )

    cells.append(md("## 6. Sector damage in ratio terms"))
    cells.append(
        code(
            "sector_focus = sector_regime.loc[sector_regime['pre_drawdown_market_strength_regime'].isin(['Strong', 'Weak'])].copy()\n"
            "display(sector_focus.round(4))\n"
            "\n"
            "plot_data = sector_focus.sort_values(['pre_drawdown_market_strength_regime', 'avg_window_drawdown_ratio'], ascending=[True, False])\n"
            "fig, axes = plt.subplots(1, 2, figsize=(15.5, 6.2), sharex=False)\n"
            "for ax, regime in zip(axes, ['Strong', 'Weak']):\n"
            "    subset = plot_data.loc[plot_data['pre_drawdown_market_strength_regime'] == regime].sort_values('avg_window_drawdown_ratio', ascending=False)\n"
            "    sns.barplot(data=subset, y='sector', x='avg_window_drawdown_ratio', hue='sector', dodge=False, legend=False, palette='viridis', ax=ax)\n"
            "    ax.axvline(1.0, color='black', linestyle='--', linewidth=1.0)\n"
            "    ax.set_title(f'Sector/SPY drawdown ratio during {regime.lower()}-market drawdowns')\n"
            "    ax.set_xlabel('sector window drawdown / SPY drawdown')\n"
            "    ax.set_ylabel('')\n"
            "plt.tight_layout()\n"
            "plt.show()"
        )
    )

    cells.append(
        md(
            "A drawdown ratio above **1.0** means the sector lost more than SPY over the same stress window. A ratio below **1.0** means the sector was more defensive than SPY. That is the cleanest way to answer the user question in ratio terms."
        )
    )

    cells.append(md("## 7. Do stretched sectors get hit differently?"))
    cells.append(
        code(
            "display(sector_stretch.round(4))\n"
            "display(sector_stretch_effect.round(4))\n"
            "\n"
            "focus = sector_stretch.loc[sector_stretch['stretch_bucket'].isin(['Rich', 'Cheap'])].copy()\n"
            "fig, ax = plt.subplots(figsize=(14, 6.2))\n"
            "sns.barplot(data=focus, y='sector', x='avg_window_drawdown_ratio', hue='stretch_bucket', palette='Set2', ax=ax)\n"
            "ax.axvline(1.0, color='black', linestyle='--', linewidth=1.0)\n"
            "ax.set_title('Sector drawdown ratio when sectors are rich versus cheap')\n"
            "ax.set_xlabel('average window drawdown ratio')\n"
            "ax.set_ylabel('')\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "fig, ax = plt.subplots(figsize=(10.5, 5.0))\n"
            "ranked = sector_stretch_effect.sort_values('stretch_to_drawdown_corr')\n"
            "sns.barplot(data=ranked, y='sector', x='stretch_to_drawdown_corr', hue='sector', dodge=False, legend=False, palette='flare', ax=ax)\n"
            "ax.axvline(0.0, color='black', linestyle='--', linewidth=1.0)\n"
            "ax.set_title('Does higher sector stretch predict more or less damage?')\n"
            "ax.set_xlabel('corr(stretch_score, sector drawdown ratio)')\n"
            "ax.set_ylabel('')\n"
            "plt.tight_layout()\n"
            "plt.show()"
        )
    )

    cells.append(md("## 8. Episode examples"))
    cells.append(
        code(
            "episode_view = episodes[[\n"
            "    'peak_date', 'onset_date', 'trough_date', 'pre_drawdown_market_strength_regime',\n"
            "    'pre_drawdown_combined_regime', 'max_drawdown', 'peak_to_trough_days',\n"
            "    'drawdown_speed_from_peak_per_day', 'trough_to_20d_return', 'trough_to_60d_return'\n"
            "]]\n"
            "display(episode_view.sort_values('max_drawdown').head(12).round(4))\n"
            "\n"
            "rich_examples = sector_episode.loc[sector_episode['stretch_bucket'] == 'Rich'][[\n"
            "    'episode_id', 'sector', 'pre_drawdown_market_strength_regime', 'stretch_score',\n"
            "    'sector_window_drawdown_ratio', 'recovery_ratio_vs_spy'\n"
            "]]\n"
            "display(rich_examples.sort_values('sector_window_drawdown_ratio', ascending=False).head(20).round(4))"
        )
    )

    cells.append(
        md(
            "## 9. What stands out\n\n"
            "1. The strong-vs-weak question is not just about depth. Some strong-market drawdowns are *faster* because the market reprices quickly, even if the total damage is smaller.\n"
            "2. VIX pace is usually the cleanest fingerprint for fast drawdown acceleration.\n"
            "3. Credit pace and macro fragility help separate short-lived shocks from more persistent weak-market regimes.\n"
            "4. Sector ratio analysis shows which groups act as leverage to SPY stress and which groups absorb it more defensively.\n"
            "5. Stretch matters, but it is sector-specific. Some rich sectors are momentum leaders that keep relative strength; others are crowded and crack harder when the market breaks."
        )
    )

    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
    }
    return nb


def main() -> None:
    notebook = build_notebook()
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    with NOTEBOOK_PATH.open("w", encoding="utf-8") as handle:
        nbf.write(notebook, handle)
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()